"""Alembic migration environment.

Wires Alembic to the application's SQLAlchemy engine and metadata so that
autogenerated migrations reflect the ORM models defined in
``app.database.models``. The database URL is read from application settings
(``app.core.config``) so migrations use exactly the same configuration as the
application runtime.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.database.base import Base

# This is the Alembic Config object, which provides access to the values within
# the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override the placeholder URL with the value from application settings so
# migrations and runtime share a single source of truth.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

# Models are imported explicitly so their tables are registered on the metadata
# before autogeneration inspects it. Model imports are intentionally deferred to
# future phases; `Base.metadata` remains valid with no tables registered.
from app.database import models  # noqa: E402,F401

#: Metadata Alembic diffs against the live database when autogenerating.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine, though an
    Engine is acceptable here as well. By skipping the Engine creation we don't
    even need a DBAPI to be available.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine and associate a connection with
    the context.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
