"""initial schema

Revision ID: 7ea33639f2a2
Revises: 
Create Date: 2026-08-03 21:37:24.608110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea33639f2a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'PROCESSING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='applicationstatus'), server_default=sa.text("'SUBMITTED'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_audit_logs_applications_application_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_application_id', 'audit_logs', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('AUTHORITY_LETTER', 'ACCOUNT_MAINTENANCE', 'ONELINK', 'TRIPARTITE', 'SCHEDULE_OF_CHARGES', 'BUSINESS_REQUIREMENT', 'FORMAL_REQUEST', 'BANK_STATEMENT', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_applications_application_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_application_id', 'documents', ['application_id'], unique=False)
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('ix_documents_processing_status', 'documents', ['processing_status'], unique=False)
    op.create_index('ix_documents_uploaded_at', 'documents', ['uploaded_at'], unique=False)
    op.create_table('feedback_dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('ocr_value', sa.Text(), nullable=True),
    sa.Column('human_value', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_feedback_dataset_applications_application_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_dataset'))
    )
    op.create_index('ix_feedback_dataset_application_id', 'feedback_dataset', ['application_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'CORRECT', 'REJECT', name='reviewdecision'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_human_reviews_applications_application_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_reviews'))
    )
    op.create_index('ix_human_reviews_application_id', 'human_reviews', ['application_id'], unique=False)
    op.create_index('ix_human_reviews_reviewer_name', 'human_reviews', ['reviewer_name'], unique=False)
    op.create_table('manual_checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('is_checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_manual_checklists_applications_application_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_checklists')),
    sa.UniqueConstraint('application_id', 'item_name', name='uq_manual_checklists_application_id_item_name')
    )
    op.create_index('ix_manual_checklists_application_id', 'manual_checklists', ['application_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'WARNING', 'PENDING_MANUAL_REVIEW', name='validationstatus'), server_default=sa.text("'PENDING_MANUAL_REVIEW'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_validation_results_applications_application_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index('ix_validation_results_application_id', 'validation_results', ['application_id'], unique=False)
    op.create_index('ix_validation_results_rule_id', 'validation_results', ['rule_id'], unique=False)
    op.create_table('human_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['human_reviews.id'], name=op.f('fk_human_corrections_human_reviews_review_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_corrections'))
    )
    op.create_index('ix_human_corrections_review_id', 'human_corrections', ['review_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=100), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ocr_results_documents_document_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_results')),
    sa.UniqueConstraint('document_id', name=op.f('uq_ocr_results_document_id'))
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ocr_result_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], name=op.f('fk_extracted_fields_ocr_results_ocr_result_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields')),
    sa.UniqueConstraint('ocr_result_id', 'field_name', name='uq_extracted_fields_ocr_result_id_field_name')
    )
    op.create_index('ix_extracted_fields_ocr_result_id', 'extracted_fields', ['ocr_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_fields_ocr_result_id', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_table('ocr_results')
    op.drop_index('ix_human_corrections_review_id', table_name='human_corrections')
    op.drop_table('human_corrections')
    op.drop_index('ix_validation_results_rule_id', table_name='validation_results')
    op.drop_index('ix_validation_results_application_id', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index('ix_manual_checklists_application_id', table_name='manual_checklists')
    op.drop_table('manual_checklists')
    op.drop_index('ix_human_reviews_reviewer_name', table_name='human_reviews')
    op.drop_index('ix_human_reviews_application_id', table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index('ix_feedback_dataset_application_id', table_name='feedback_dataset')
    op.drop_table('feedback_dataset')
    op.drop_index('ix_documents_uploaded_at', table_name='documents')
    op.drop_index('ix_documents_processing_status', table_name='documents')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_index('ix_documents_application_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_audit_logs_application_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('applications')
    # ### end Alembic commands ###
