"""Add rule engine validation columns and visual detections

Revision ID: aa90cb91200c
Revises: c9146e38b398
Create Date: 2026-08-05 23:19:15.551179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa90cb91200c'
down_revision: Union[str, Sequence[str], None] = 'c9146e38b398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('is_present', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_engine', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_visual_detection_results_documents_document_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_detection_results')),
    sa.UniqueConstraint('document_id', 'detection_type', name='uq_visual_detection_results_document_id_detection_type')
    )
    op.create_index('ix_visual_detection_results_document_id', 'visual_detection_results', ['document_id'], unique=False)
    op.add_column('validation_results', sa.Column('related_document_ids', sa.JSON(), nullable=True))
    op.add_column('validation_results', sa.Column('related_field_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_results', 'related_field_names')
    op.drop_column('validation_results', 'related_document_ids')
    op.drop_index('ix_visual_detection_results_document_id', table_name='visual_detection_results')
    op.drop_table('visual_detection_results')
    # ### end Alembic commands ###
