"""Extend extracted_fields for confidence scoring.

Adds the per-field confidence and human-verification columns consumed by the
Phase 8 confidence scoring module. ``confidence_source`` records which source
produced the score, ``confidence_reason`` explains it, ``verification_status``
tracks the field's review state and the remaining columns capture the human
review outcome (corrected value, verified flag, reviewer and timestamp). All
columns except ``human_verified`` are nullable and additive, so the table
remains safe for any existing rows and future OCR writers.

Revision ID: c9146e38b398
Revises: 7d5f0708871e
Create Date: 2026-08-05 11:49:38.355403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9146e38b398'
down_revision: Union[str, Sequence[str], None] = '7d5f0708871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_fields', sa.Column('confidence_source', sa.String(length=50), nullable=True))
    op.add_column('extracted_fields', sa.Column('confidence_reason', sa.Text(), nullable=True))
    op.add_column('extracted_fields', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('extracted_fields', sa.Column('human_corrected_value', sa.Text(), nullable=True))
    op.add_column('extracted_fields', sa.Column('human_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('extracted_fields', sa.Column('reviewer', sa.String(length=255), nullable=True))
    op.add_column('extracted_fields', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_fields', 'reviewed_at')
    op.drop_column('extracted_fields', 'reviewer')
    op.drop_column('extracted_fields', 'human_verified')
    op.drop_column('extracted_fields', 'human_corrected_value')
    op.drop_column('extracted_fields', 'verification_status')
    op.drop_column('extracted_fields', 'confidence_reason')
    op.drop_column('extracted_fields', 'confidence_source')
    # ### end Alembic commands ###
