"""Add document processing columns to ocr_results.

Extends the Phase 2 ``ocr_results`` table so the document processing module can
persist the extraction metrics alongside the raw text the table already holds.
``processing_method`` records how the text was obtained (native text extraction
or OCR), ``page_count`` and ``character_count`` summarise the extraction and
``processed_at`` timestamps when it completed. All columns are nullable and
additive, so existing rows and any other OCR-writing module remain unaffected.

Revision ID: cd87b35daee9
Revises: dfb3fb1dced2
Create Date: 2026-08-04 10:52:18.725444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd87b35daee9'
down_revision: Union[str, Sequence[str], None] = 'dfb3fb1dced2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('processing_method', sa.String(length=50), nullable=True))
    op.add_column('ocr_results', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('ocr_results', sa.Column('character_count', sa.Integer(), nullable=True))
    op.add_column('ocr_results', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_results', 'processed_at')
    op.drop_column('ocr_results', 'character_count')
    op.drop_column('ocr_results', 'page_count')
    op.drop_column('ocr_results', 'processing_method')
    # ### end Alembic commands ###
