"""Add technical validation columns to validation_results.

Extends the Phase 2 ``validation_results`` table so the technical validation
module can persist one row per technical check while reusing the existing table.
``document_id`` scopes each check to the document being validated (rule-engine
rows keep it ``NULL``); ``blur_score`` and ``rotation_angle`` carry the numeric
measurements produced by the blur/rotation checks and ``file_format`` records
the detected format. All columns are nullable and additive, so existing rows
and the rule engine remain unaffected.

Revision ID: dfb3fb1dced2
Revises: d1f7c4a9e2b3
Create Date: 2026-08-03 23:34:53.770020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb3fb1dced2'
down_revision: Union[str, Sequence[str], None] = 'd1f7c4a9e2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_results', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('validation_results', sa.Column('blur_score', sa.Float(), nullable=True))
    op.add_column('validation_results', sa.Column('rotation_angle', sa.Float(), nullable=True))
    op.add_column('validation_results', sa.Column('file_format', sa.String(length=10), nullable=True))
    op.create_index('ix_validation_results_document_id', 'validation_results', ['document_id'], unique=False)
    op.create_foreign_key(op.f('fk_validation_results_documents_document_id'), 'validation_results', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_validation_results_documents_document_id'), 'validation_results', type_='foreignkey')
    op.drop_index('ix_validation_results_document_id', table_name='validation_results')
    op.drop_column('validation_results', 'file_format')
    op.drop_column('validation_results', 'rotation_angle')
    op.drop_column('validation_results', 'blur_score')
    op.drop_column('validation_results', 'document_id')
    # ### end Alembic commands ###
