"""ORM models package.

Importing this package registers every model on ``Base.metadata``. Alembic
imports ``app.database.models`` in ``env.py`` so autogenerated migrations see
the complete schema; application code can import models from their individual
modules for a smaller import surface.
"""

from app.database.models.application import Application
from app.database.models.audit_log import AuditLog
from app.database.models.document import Document
from app.database.models.document_analysis_result import DocumentAnalysisResult
from app.database.models.extracted_field import ExtractedField
from app.database.models.feedback_dataset import FeedbackEntry
from app.database.models.human_correction import HumanCorrection
from app.database.models.human_review import HumanReview
from app.database.models.manual_checklist import ManualChecklist
from app.database.models.ocr_result import OCRResult
from app.database.models.refresh_token import RefreshToken
from app.database.models.user import User
from app.database.models.validation_result import ValidationResult
from app.database.models.visual_detection import VisualDetection

__all__ = [
    "Application",
    "AuditLog",
    "Document",
    "DocumentAnalysisResult",
    "ExtractedField",
    "FeedbackEntry",
    "HumanCorrection",
    "HumanReview",
    "ManualChecklist",
    "OCRResult",
    "RefreshToken",
    "User",
    "ValidationResult",
    "VisualDetection",
]
