"""Declarative ORM base.

Provides the single declarative base class every future ORM model will inherit
from. Models are not defined in Phase 1; this module only establishes the shared
metadata and a consistent naming convention so that constraints generated by
Alembic migrations follow a predictable, searchable pattern.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

#: Naming convention applied to all constraints and indexes generated by
#: SQLAlchemy and Alembic. A predictable naming scheme makes constraint names
#: stable across environments and easier to reference in migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(referred_table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all ORM models.

    Subclasses of this class are registered on ``Base.metadata``, which Alembic
    uses as the source of truth for autogenerated migrations.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
